Repository MIT-Emerging-Talent/ET6-foundations-group-17, pull requests merged in 2025-01, with the labels that each got.

#29 Collaboration update
  collaboration/README.md
  collaboration/constraints.md
Labels: documentation, enhancement

#41 FizzBuzz Game
  solutions/fizz_buzz_game.py
  solutions/tests/test_fizz_buzz_game.py
Labels: challenge

#42 Rock-Paper-Scissor Game
  solutions/rock_paper_scissor.py
  solutions/tests/test_rock_paper_scissor.py
Labels: challenge

#45 Solution for prime filter challenge
  solutions/prime_filter_challenge.py
  tests/test_prime_filter_challenge.py
Labels: challenge

#53 Number Sort Challenge
  solutions/number_sort.py
  solutions/tests/test_number_sort.py
Labels: challenge

#38 Solution for mirror words challenge
  solutions/mirror_words_challenge.py
  solutions/tests/test_mirror_words_challenge.py
Labels: challenge

#71 Refactored Number Guessing Game Code
  solutions/number_guessing_game.py
  solutions/tests/test_number_guessing_game.py
Labels: challenge

#102 The Palindrome🔝
  solutions/is_palindrome.py
  solutions/tests/test_is_palindrome.py
Labels: challenge

#72 Challenge 2 - Pythagorean Triplets Finder
  solutions/find_pythagorean_triplets.py
  solutions/tests/test_find_pythagorean_triplets.py
Labels: challenge

#107 Update retrospective.md
  collaboration/retrospective.md
Labels: help wanted, Discussion
